### ISSUE TITLE
Release checklist for v1.6.0

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#3623]
@vmware-tanzu/velero-maintainers let's all check these boxes as we get thru the steps.

## Beta and prior to the first RC release
- [x] no major bugs outstanding (current issues: #3599, #3624)
- [x] unit tests pass
- [x] e2e tests passing on Kind
- [x] e2e tests passing on vSphere
- [x] e2e tests passing on AWS

## Any RC + plugin release
Manual tests need to be run before the plugins are released. Documentation for manual testing (to be updated after merge): https://github.com/vmware-tanzu/velero/pull/3601
- [ ] manual tests with RC and upgraded plugin passing on:
    - [x]  Kind [@ashish-amarnath]
    - [x] AWS - [@carlisia]
    - [ ] vSphere
    - [x] GCP [@ashish-amarnath]
    - [ ] Azure
- [ ] test [upgrading to RC](https://velero.io/docs/main/upgrade-to-1.6/#docs) on:
    - [x]  Kind
    - [x] AWS - [@carlisia]
    - [x] vSphere
    - [x] GCP [@ashish-amarnath]
    - [ ] Azure
- [x] test restic [@ashish-amarnath]

⚠️ e2e tests need to run against the latest k8s and earliest supported k8s for each plugin

Note: this checklist follows the (not yet merged) release criteria list: https://deploy-preview-3598--velero.netlify.app/docs/main/release-instructions/#release-criteria.

**Comment by dsu-igeek** [comment]
Please add Azure to the release checklist

**Comment by ashish-amarnath** [comment]
Please add restic as well

**Comment by carlisia** [comment]
I ran these tests and they were all successful:

Test 1:
Verify that a backup and restore using Volume Snapshots can be performed
https://asciinema.org/a/KB67j2jcYPNOulebx9WQyYXEO

Test 2:
Verify that an installation using the v1.6.0-rc.2 version can be used to restore from backups created with the v1.5.3 version 
recording 1: backup with v1.5.3, then install v1.6.0-rc.2 / break 
https://asciinema.org/a/HWPACBQKdBIS49U8TF0pmIRnq
recording 2: restore previous backup using v1.6.0-rc.2
https://asciinema.org/a/O8l7Y0AIWqrVEYyV8iZ2Bvfly

Test 3:
Ensure v1.6.0-rc.2 compatibility with plugin v1.1.0
https://asciinema.org/a/sJcNXx2Jjht4AHbX9r2uYQxZv

Test 4:
Upgrade the install from v1.5.3 to v1.6.0-rc.2
https://asciinema.org/a/HNdS0ouAT7XQeWwPBZIje0N6W

**Comment by carlisia** [comment]
@vmware-tanzu/velero-owners + @jenting: closing this as it's all been done.
