### ISSUE TITLE
Migrate the exsting kubebuilder based controllers to kubebuilder v3

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#4307]
As the kubebuilder v2 is to be deprecated, moving forward we refactor the controllers to be based on kubebuilder v3.

Meanwhile there have been controllers that have been refactored to be based on kubebuilder v2, and we should make sure all the `refactored` controllers are based on one version of kubebuilder.  Therefore, we need to migrate these controllers to be based on kubebuilder v3 in the codebase.

b/c kubebuilder v3 will only support v1 CRD, we need to make sure this migration doesn't break the upgrade scenario of velero.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
@blackpiglet
Let's do some initial investigation and decide if that's possible for v1.8
Feel free to convert this issue to an epic so that it can be broken down into multiple sub-tasks.

**Comment by eleanor-millman** [comment]
@reasonerjt do we expect this to be done as part of the Kubebuilder tech debt work for 1.8 or should I remove it from the 1.8 milestone?

**Comment by blackpiglet** [comment]
- [ ] Migrate BackupStorageLocation from kubebuilder v2 to v3 - https://github.com/vmware-tanzu/velero/issues/4369
- [ ] Migrate DownloadRequest from kubebuilder v2 to v3 - https://github.com/vmware-tanzu/velero/issues/4370
- [ ] Migrate ServerStatusRequest from kubebuilder v2 to v3 - https://github.com/vmware-tanzu/velero/issues/4371

**Comment by blackpiglet** [comment]
All child issues are resolved. Close it.
