### ISSUE TITLE
Migrate controllers to kubebuilder in v1.9

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#4540]
**Describe the problem/challenge you have**
Use this task to trace controller migration to kubebuilder as part of Velero modernization task.

**Describe the solution you'd like**
The child tasks are used to trace all controllers are supposed to migrate in Velero release v1.9

- [x] convert pod volume backup - https://github.com/vmware-tanzu/velero/issues/3454
- [x] convert pod volume restore - https://github.com/vmware-tanzu/velero/issues/4134
- [x] convert backup sync controller - #4135
**Opportunistic:**
- [x] convert delete backup request - https://github.com/vmware-tanzu/velero/issues/4669
- [x] convert restic repository - https://github.com/vmware-tanzu/velero/issues/4670
- [x] convert schedule - https://github.com/vmware-tanzu/velero/issues/4671
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"
