### ISSUE TITLE
Bump the Ginkgo version to v2

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#7872]
- [x] Replace RunSpecsWithDefaultAndCustomReporters - #7957 
  - [x] Adjust default timeout - #7958 
  - [x] Use labels instead of regex - #7959
  - [ ] Support running test parallelly - #7960 
  - [x] Bump Ginkgo to v2 - #7961 

**Describe the problem/challenge you have**

Ginkgo v2 supports more features, and the Ginkgo v1 is not maintained anymore.
https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#upgrading-to-ginkgo-20
https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#aborting-the-test-suite

Propose to upgrade the Velero E2E using Ginkgo to v2 to utilize the new functionality.

**Describe the solution you'd like**

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by kaovilai** [comment]
We've done this in OADP in the past. If you can break the tasks out I can assist here.

**Comment by blackpiglet** [comment]
@kaovilai 
Great.
Were there any issues or PRs on the OADP side that I can take as a reference?

**Comment by kaovilai** [comment]
This is the main one we did to move to v2 https://github.com/openshift/oadp-operator/pull/560

I think we had a mix of both in go.mod initially but eventually removed v1 references.

**Comment by kaovilai** [comment]
[Last v1 removal](https://github.com/openshift/oadp-operator/commit/c3cbfd650606d9ce5e5518c2ecd0655ff4c19abc#diff-522ed98795d88bff1df848662d1eee2a296ed9a37b852695f82583865d198092) was simply
```diff
-	"github.com/onsi/ginkgo"
+	"github.com/onsi/ginkgo/v2"
```

**Comment by blackpiglet** [comment]
@kaovilai 
Thanks.
After reading some Ginkgo documents, I broke this Epic task into sub-tasks.
I'm still getting familiar with the Ginkgo framework. There could be something inaccurate, or something important is still missing.
Appreciate any help.

**Comment by reasonerjt** [comment]
We'll track #7960 separately.
